In [1]:
import numpy as np

In [2]:
score = np.array([13, 12, 6, 20, 12, 15, 17])
score

array([13, 12,  6, 20, 12, 15, 17])

In [3]:
print(score)

[13 12  6 20 12 15 17]


In [4]:
print(score.ndim)

1


In [5]:
score.shape

(7,)

In [6]:
score [1] # 12
score[1:6] # 12, 6, ...

array([12,  6, 20, 12, 15])

In [7]:
s = np.sort(score)

In [8]:
s

array([ 6, 12, 12, 13, 15, 17, 20])

In [9]:
uscore = np.unique(score)

In [10]:
uscore

array([ 6, 12, 13, 15, 17, 20])

In [11]:
x = score / 2

In [12]:
x

array([ 6.5,  6. ,  3. , 10. ,  6. ,  7.5,  8.5])

In [13]:
print(x)

[ 6.5  6.   3.  10.   6.   7.5  8.5]


In [14]:
np.sum(score)

np.int64(95)

In [15]:
print(np.sum(score))

95


In [16]:
np.where(score < 10, 10, np.where(score <= 17, 17, 20))

array([17, 17, 10, 20, 17, 17, 17])

In [17]:
a = np.array([11, 20, 13, 14, 18, 6])

In [18]:
x = np.where(a == 13)
print(x)

(array([2]),)


In [19]:
x

(array([2]),)

In [20]:
x[0]

array([2])

In [22]:
print(type(np.where(a%2 == 0)))

<class 'tuple'>


In [26]:
s = np.array([1, 2, 3, 4, 5])
c = s[1:4].copy()
s[1] = 7
print(s)
print(c)

[1 7 3 4 5]
[2 3 4]


In [27]:
a = np.array([1, 2])
b = a.view()
a[1] = 7
print(a, b)

[1 7] [1 7]


In [28]:
a = np.array([11, 20, 18, 14, 15, 13])
x = np.searchsorted(a, 12)
print(np.sort(a))
print(x)

[11 13 14 15 18 20]
1


In [29]:
a = np.array([12, 9, 18])
x = [True, False, True]
b = a[x]
print(b)

[12 18]


In [32]:
print(
    np.zeros(3),
    np.full(3, 20),
    np.arange(3),
    np.random.randn(3)
)

[0. 0. 0.] [20 20 20] [0 1 2] [-0.15579475  0.11504119 -0.63291778]


In [36]:
a = np.array([1, 2, 3, 4, 5, 6])
n = np.array_split(a, 2)
print(n[0][2])

3


In [37]:
x = np.array([[1, 2 ,3], [4, 5, 6], [7, 8, 9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
x.shape

(3, 3)

In [40]:
x.ndim

2

In [41]:
x[0]

array([1, 2, 3])

In [42]:
x[0][0]

np.int64(1)

In [43]:
x[1][1]

np.int64(5)

In [44]:
x[-1][-1]

np.int64(9)

In [45]:
x[0][-1]

np.int64(3)

In [46]:
x[-1][0]

np.int64(7)

In [47]:
x[0, 1]

np.int64(2)

In [48]:
x[0, 1:3]

array([2, 3])

In [49]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
b = a.reshape(2, 4)

In [50]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
z = np.arange(2, 101, 2).reshape(10, 5)

In [57]:
z

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [59]:
z.shape

(10, 5)

In [60]:
z.ndim

2

In [61]:
a = np.arange(1, 10).reshape(3, 3)
print(np.sum(a))
print(np.sum(a, axis= 0))
print(a)

45
[12 15 18]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
a = np.random.randint(1, 100, size= (10, 10))
b = np.random.randint(1, 100, size= (10, 10))
print(a)
print()
print(b)
print()
print(np.concatenate((a, b), axis= 0))

[[16 58 44  1 70 17 87 74 58 22]
 [29 88 15 12  2 86 17 27 41 86]
 [31 38 46 37 69 23 42 22 86 74]
 [98 18 31 47 82 48 81 21 66 94]
 [85 44 35 68 85 88 24  8 48 45]
 [80 16 26 90 86 91 87 29 95 25]
 [60 92 96 24 20 13 71 60 16 21]
 [29 36 52 95 20 64 71 72 98 28]
 [30 98 89 36 56 72 25 51 18 17]
 [ 8 73 35 41 45 98 83 11 20 98]]

[[90 85  9 65 30 91 10 42 40 55]
 [32 69 58 73 25 53 77 58 45 37]
 [46 26 48 53 84  9 29 48 58 23]
 [ 8 15 58  9  5 62 17 22 69 96]
 [98 57 67 65 40 53 25 12 68 96]
 [34 48 43 48  1 83 82 66 25 66]
 [57 12  9 63 29 25 62 23 56  1]
 [24 50 56 24 35 55 91  4  4 35]
 [ 2 15 22 11 55 23 97 96 38 67]
 [70 19 18 84 73 19 89 75 77 96]]

[[16 58 44  1 70 17 87 74 58 22]
 [29 88 15 12  2 86 17 27 41 86]
 [31 38 46 37 69 23 42 22 86 74]
 [98 18 31 47 82 48 81 21 66 94]
 [85 44 35 68 85 88 24  8 48 45]
 [80 16 26 90 86 91 87 29 95 25]
 [60 92 96 24 20 13 71 60 16 21]
 [29 36 52 95 20 64 71 72 98 28]
 [30 98 89 36 56 72 25 51 18 17]
 [ 8 73 35 41 45 98 83 11 20 98]
 [90 8

In [88]:
a = np.arange(1, 7).reshape(3, 2)
a.swapaxes(1, 0)

array([[1, 3, 5],
       [2, 4, 6]])

In [90]:
a = np.arange(1, 7).reshape(2, 3)
print(a)
np.transpose(a)

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [92]:
np.flipud(a)

array([[4, 5, 6],
       [1, 2, 3]])

In [96]:
a = np.random.randint(1, 10, size= 10)
b = np.random.randint(1, 10, size= 10)
print((a == b).sum())
print(a == b)

3
[False False False False False  True  True False  True False]


In [98]:
a = np.arange(1, 4)
b = np.arange(4, 7)
c = np.stack((a, b), axis= 1)
print(c)

[[1 4]
 [2 5]
 [3 6]]
